name: jogo_nim
description: "A new Flutter project."

publish_to: "none" # Remove this line if you desejar publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.6 # Adiciona a dependência do shared_preferences

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true